name: "Runner - Python"
inputs:
  version:
    description: "version"
    required: true
  source:
    description: "source"
    default: "."
runs:
  using: "composite"
  steps:
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: ${{ inputs.version }}
    - name: Install dependencies
      shell: bash
      working-directory: ${{ inputs.source }}
      run: pip install -r requirements.txt