name: "CICD - Build And Test"
inputs:
  component_type:
    description: "OpsLevel component_type"
    required: true
  language:
    description: "language"
    required: true
  version:
    description: "version"
    required: true
  source:
    description: "source"
    default: "."
runs:
  using: "composite"
  steps:
    - name: Build
      uses: libbyf/github-actions-poc/.github/actions/cicd/build@main
      with:
        component_type: ${{ inputs.component_type }}
        language: ${{ inputs.language }}
        version: ${{ inputs.version }}
        source: ${{ inputs.source }}
    - name: Test Micro-Service }}
      if: inputs.component_type == 'micro-service'
      uses: libbyf/github-actions-poc/.github/actions/cicd/components/micro-service/test@main
      with:
        language: ${{ inputs.language }}
        source: ${{ inputs.source }}